# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: Template to create a simple EC2 instance with Ubuntu Server
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-083654bd07b5da81d'
      InstanceType: t2.micro
      SubnetId: subnet-065b60559f922c32a

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
