version: 2.1

orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3

commands:
  destroy_infrastructure:
    steps:
      - run:
          name: Destroy infra environment
          when: on_fail
          command: |
            /usr/local/bin/aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --region us-east-1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
      - destroy_infrastructure

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['cb:af:63:fd:d4:66:da:e4:ff:80:49:70:14:0b:06:45']
      - run:
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: Run Ansible and setup server
          command: ansible-playbook main.yml -i inventory

  smoke_tests:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: Install AWS CLI dependencies
          working_directory: /tmp
          command: |
            apt-get update && sudo apt-get install -yy less
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Run smoke test on website
          command: |
            URL="http://ec2-3-91-176-57.compute-1.amazonaws.com:3000/"
            if curl -s --head ${URL}
            then
            return 1
            else
            return 1
            fi
      - destroy_infrastructure

workflows:
  infrastructure_workflow:
    jobs:
      # - create_infrastructure
      # - configure_infrastructure
      - smoke_tests
        # requires:
        #   - configure_infrastructure
