version: 2.1

orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3

commands:
  destroy_infrastructure:
    steps:
      - run:
          name: Destroy infra environment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name circle-ci-infrastructure --region us-east-1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name circle-ci-infrastructure \
              --region us-east-1
      - destroy_infrastructure

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['cb:af:63:fd:d4:66:da:e4:ff:80:49:70:14:0b:06:45']
      - run:
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: Run Ansible and setup server
          command: ansible-playbook main.yml -i inventory

  smoke_tests:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add --update curl
            pip install awscli
      - run:
          name: Run smoke test on website
          command: |
            URL="http://ec2-3-91-176-57.compute-1.amazonaws.com:3000/"
            if curl -s --head ${URL}
            then
            return 1
            else
            return 1
            fi
      - destroy_infrastructure

workflows:
  infrastructure_workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
      - smoke_tests
          requires:
            - configure_infrastructure
